# Generated by Django 4.0.2 on 2022-02-20 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='priority',
            new_name='priority_order',
        ),
    ]
